# Generated by Django 5.0 on 2024-04-22 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flow', '0002_charttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='項番')),
                ('status', models.IntegerField(max_length=50, verbose_name='ステータス')),
                ('number', models.IntegerField(verbose_name='共通社員番号')),
                ('authority', models.IntegerField(verbose_name='権限')),
                ('gmail', models.CharField(max_length=255, verbose_name='メールアドレス')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('avator', models.TextField(verbose_name='アバターのURL')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeChart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='項番')),
                ('status', models.IntegerField(verbose_name='ステータス')),
                ('permission', models.IntegerField(verbose_name='他ユーザ権限')),
                ('other_ids', models.TextField(verbose_name='他ユーザID')),
                ('range_permission', models.IntegerField(verbose_name='編集権限範囲')),
                ('created_at', models.CharField(max_length=14, verbose_name='作成日時')),
                ('updated_at', models.CharField(max_length=14, verbose_name='更新日時')),
                ('edge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.edge')),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.node')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.charttype')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
