# Generated by Django 5.0 on 2024-04-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeechart',
            name='name',
            field=models.CharField(default='無題のフロー', max_length=255, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.IntegerField(verbose_name='ステータス'),
        ),
    ]
