# Generated by Django 5.0 on 2024-04-22 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeechart_name_alter_employee_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='avator',
            new_name='avatar',
        ),
    ]
