# Generated by Django 5.0 on 2024-04-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_rename_avator_employee_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeechart',
            old_name='edge_id',
            new_name='edge',
        ),
        migrations.RenameField(
            model_name='employeechart',
            old_name='node_id',
            new_name='node',
        ),
        migrations.RenameField(
            model_name='employeechart',
            old_name='type_id',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='employeechart',
            old_name='user_id',
            new_name='user',
        ),
    ]
