# Generated by Django 5.0 on 2024-04-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='項番')),
                ('edge', models.TextField(verbose_name='エッジデータ')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='項番')),
                ('node', models.TextField(verbose_name='ノードデータ')),
            ],
        ),
    ]
