# Generated by Django 5.0 on 2024-04-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='項番')),
                ('name', models.CharField(max_length=255, verbose_name='タイプ名')),
                ('img_url', models.TextField(blank=True, null=True, verbose_name='画像URL')),
            ],
        ),
    ]
